from collections import namedtuple

BatmanModTerm = namedtuple("BatmanModTerm", ["attr", "team", "stat", "bounds"])

BATMAN_MOD_TERMS = [    
    BatmanModTerm("LOVE", "opp", "Ruthlessness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Unthwackability",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Overpowerment",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Shakespearianism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Coldness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Tragicness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Patheticism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Thwackability",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Divinity",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Moxie",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Musclitude",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "Martyrdom",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MeanOmniscience",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MeanTenaciousness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MeanWatchfulness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MeanAnticapitalism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MeanChasiness",[[-5, 5], [0, 1], [1, 1.5]]),    
    BatmanModTerm("LOVE", "opp", "MeanLaserlikeness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MeanBaseThirst",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MeanContinuation",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MeanGroundFriction",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MeanIndulgence",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MaxOmniscience",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MaxTenaciousness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MaxWatchfulness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MaxAnticapitalism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MaxChasiness",[[-5, 5], [0, 1], [1, 1.5]]),    
    BatmanModTerm("LOVE", "opp", "MaxLaserLikeness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MaxBaseThirst",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MaxContinuation",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MaxGroundFriction",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("LOVE", "opp", "MaxIndulgence",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "Ruthlessness", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "Unthwackability", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "Overpowerment", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "Shakespearianism", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "Coldness", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "Tragicness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "Patheticism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "Thwackability",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "Divinity",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "Moxie",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "Musclitude",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "Martyrdom",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "MeanOmniscience", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "MeanTenaciousness", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "MeanWatchfulness", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "MeanAnticapitalism", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "MeanChasiness", [[-15, 10], [-3, 4], [-3, 4]]),    
    BatmanModTerm("EXTRA_STRIKE", "same", "MeanLaserlikeness", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "MeanBaseThirst", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "MeanContinuation", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "MeanGroundFriction", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "MeanIndulgence", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "MaxOmniscience", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "MaxTenaciousness", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "MaxWatchfulness", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "MaxAnticapitalism", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "opp", "MaxChasiness", [[-15, 10], [-3, 4], [-3, 4]]),    
    BatmanModTerm("EXTRA_STRIKE", "same", "MaxLaserLikeness", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "MaxBaseThirst", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "MaxContinuation", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "MaxGroundFriction", [[-15, 10], [-3, 4], [-3, 4]]),
    BatmanModTerm("EXTRA_STRIKE", "same", "MaxIndulgence", [[-15, 10], [-3, 4], [-3, 4]]),    
    BatmanModTerm("O_NO", "opp", "Ruthlessness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "Unthwackability",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "Overpowerment",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "Shakespearianism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "Coldness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "Tragicness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "Patheticism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "Thwackability",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "Divinity",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "Moxie",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "Musclitude",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "Martyrdom",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "MeanOmniscience",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "MeanTenaciousness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "MeanWatchfulness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "MeanAnticapitalism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "MeanChasiness",[[-5, 5], [0, 1], [1, 1.5]]),    
    BatmanModTerm("O_NO", "same", "MeanLaserlikeness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "MeanBaseThirst",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "MeanContinuation",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "MeanGroundFriction",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "MeanIndulgence",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "MaxOmniscience",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "MaxTenaciousness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "MaxWatchfulness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "MaxAnticapitalism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "opp", "MaxChasiness",[[-5, 5], [0, 1], [1, 1.5]]),    
    BatmanModTerm("O_NO", "same", "MaxLaserLikeness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "MaxBaseThirst",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "MaxContinuation",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "MaxGroundFriction",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("O_NO", "same", "MaxIndulgence",[[-5, 5], [0, 1], [1, 1.5]]),    
    BatmanModTerm("HIGH_PRESSURE", "same", "Tragicness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "Patheticism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "Thwackability",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "Divinity",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "Moxie",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "Musclitude",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "Martyrdom",[[-5, 5], [0, 1], [1, 1.5]]),    
    BatmanModTerm("HIGH_PRESSURE", "same", "MeanLaserlikeness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "MeanBaseThirst",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "MeanContinuation",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "MeanGroundFriction",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "MeanIndulgence",[[-5, 5], [0, 1], [1, 1.5]]),    
    BatmanModTerm("HIGH_PRESSURE", "same", "MaxLaserLikeness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "MaxBaseThirst",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "MaxContinuation",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "MaxGroundFriction",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("HIGH_PRESSURE", "same", "MaxIndulgence",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "Ruthlessness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "Unthwackability",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "Overpowerment",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "Shakespearianism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "Coldness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "Tragicness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "Patheticism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "Thwackability",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "Divinity",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "Moxie",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "Musclitude",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "Martyrdom",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "MeanOmniscience",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "MeanTenaciousness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "MeanWatchfulness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "MeanAnticapitalism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "MeanChasiness",[[-5, 5], [0, 1], [1, 1.5]]),    
    BatmanModTerm("BASE_INSTINCTS", "same", "MeanLaserlikeness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "MeanBaseThirst",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "MeanContinuation",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "MeanGroundFriction",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "MeanIndulgence",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "MaxOmniscience",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "MaxTenaciousness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "MaxWatchfulness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "MaxAnticapitalism",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "opp", "MaxChasiness",[[-5, 5], [0, 1], [1, 1.5]]),    
    BatmanModTerm("BASE_INSTINCTS", "same", "MaxLaserLikeness",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "MaxBaseThirst",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "MaxContinuation",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "MaxGroundFriction",[[-5, 5], [0, 1], [1, 1.5]]),
    BatmanModTerm("BASE_INSTINCTS", "same", "MaxIndulgence",[[-5, 5], [0, 1], [1, 1.5]])
]