from collections import namedtuple

BallParkTerm = namedtuple("BallParkTerm", ["ballparkstat", "playerstat", "bounds"])
DefaultBounds = [[-3, 3], [0, 1], [1, 1.5]]

BALLPARK_TERMS = [    
    BallParkTerm("grandiosity", "Ruthlessness", DefaultBounds),
    BallParkTerm("grandiosity", "Unthwackability", DefaultBounds),
    BallParkTerm("grandiosity", "Overpowerment", DefaultBounds),
    BallParkTerm("grandiosity", "Shakespearianism", DefaultBounds),
    BallParkTerm("grandiosity", "Coldness", DefaultBounds),
    BallParkTerm("grandiosity", "Omniscience", DefaultBounds),
    BallParkTerm("grandiosity", "Tenaciousness", DefaultBounds),
    BallParkTerm("grandiosity", "Watchfulness", DefaultBounds),
    BallParkTerm("grandiosity", "Anticapitalism", DefaultBounds),
    BallParkTerm("grandiosity", "Chasiness", DefaultBounds),
    BallParkTerm("grandiosity", "Tragicness", DefaultBounds),
    BallParkTerm("grandiosity", "Patheticism", DefaultBounds),
    BallParkTerm("grandiosity", "Thwackability", DefaultBounds),
    BallParkTerm("grandiosity", "Divinity", DefaultBounds),
    BallParkTerm("grandiosity", "Moxie", DefaultBounds),
    BallParkTerm("grandiosity", "Musclitude", DefaultBounds),
    BallParkTerm("grandiosity", "Martyrdom", DefaultBounds),
    BallParkTerm("grandiosity", "Laserlikeness", DefaultBounds),
    BallParkTerm("grandiosity", "BaseThirst", DefaultBounds),
    BallParkTerm("grandiosity", "Continuation", DefaultBounds),
    BallParkTerm("grandiosity", "GroundFriction", DefaultBounds),
    BallParkTerm("grandiosity", "Indulgence", DefaultBounds),       
    BallParkTerm("obtuseness", "Ruthlessness", DefaultBounds),
    BallParkTerm("obtuseness", "Unthwackability", DefaultBounds),
    BallParkTerm("obtuseness", "Overpowerment", DefaultBounds),
    BallParkTerm("obtuseness", "Shakespearianism", DefaultBounds),
    BallParkTerm("obtuseness", "Coldness", DefaultBounds),
    BallParkTerm("obtuseness", "Omniscience", DefaultBounds),
    BallParkTerm("obtuseness", "Tenaciousness", DefaultBounds),
    BallParkTerm("obtuseness", "Watchfulness", DefaultBounds),
    BallParkTerm("obtuseness", "Anticapitalism", DefaultBounds),
    BallParkTerm("obtuseness", "Chasiness", DefaultBounds),
    BallParkTerm("obtuseness", "Tragicness", DefaultBounds),
    BallParkTerm("obtuseness", "Patheticism", DefaultBounds),
    BallParkTerm("obtuseness", "Thwackability", DefaultBounds),
    BallParkTerm("obtuseness", "Divinity", DefaultBounds),
    BallParkTerm("obtuseness", "Moxie", DefaultBounds),
    BallParkTerm("obtuseness", "Musclitude", DefaultBounds),
    BallParkTerm("obtuseness", "Martyrdom", DefaultBounds),
    BallParkTerm("obtuseness", "Laserlikeness", DefaultBounds),
    BallParkTerm("obtuseness", "BaseThirst", DefaultBounds),
    BallParkTerm("obtuseness", "Continuation", DefaultBounds),
    BallParkTerm("obtuseness", "GroundFriction", DefaultBounds),
    BallParkTerm("obtuseness", "Indulgence", DefaultBounds),    
    BallParkTerm("ominousness", "Ruthlessness", DefaultBounds),
    BallParkTerm("ominousness", "Unthwackability", DefaultBounds),
    BallParkTerm("ominousness", "Overpowerment", DefaultBounds),
    BallParkTerm("ominousness", "Shakespearianism", DefaultBounds),
    BallParkTerm("ominousness", "Coldness", DefaultBounds),
    BallParkTerm("ominousness", "Omniscience", DefaultBounds),
    BallParkTerm("ominousness", "Tenaciousness", DefaultBounds),
    BallParkTerm("ominousness", "Watchfulness", DefaultBounds),
    BallParkTerm("ominousness", "Anticapitalism", DefaultBounds),
    BallParkTerm("ominousness", "Chasiness", DefaultBounds),
    BallParkTerm("ominousness", "Tragicness", DefaultBounds),
    BallParkTerm("ominousness", "Patheticism", DefaultBounds),
    BallParkTerm("ominousness", "Thwackability", DefaultBounds),
    BallParkTerm("ominousness", "Divinity", DefaultBounds),
    BallParkTerm("ominousness", "Moxie", DefaultBounds),
    BallParkTerm("ominousness", "Musclitude", DefaultBounds),
    BallParkTerm("ominousness", "Martyrdom", DefaultBounds),
    BallParkTerm("ominousness", "Laserlikeness", DefaultBounds),
    BallParkTerm("ominousness", "BaseThirst", DefaultBounds),
    BallParkTerm("ominousness", "Continuation", DefaultBounds),
    BallParkTerm("ominousness", "GroundFriction", DefaultBounds),
    BallParkTerm("ominousness", "Indulgence", DefaultBounds),    
    BallParkTerm("viscosity", "Ruthlessness", DefaultBounds),
    BallParkTerm("viscosity", "Unthwackability", DefaultBounds),
    BallParkTerm("viscosity", "Overpowerment", DefaultBounds),
    BallParkTerm("viscosity", "Shakespearianism", DefaultBounds),
    BallParkTerm("viscosity", "Coldness", DefaultBounds),
    BallParkTerm("viscosity", "Omniscience", DefaultBounds),
    BallParkTerm("viscosity", "Tenaciousness", DefaultBounds),
    BallParkTerm("viscosity", "Watchfulness", DefaultBounds),
    BallParkTerm("viscosity", "Anticapitalism", DefaultBounds),
    BallParkTerm("viscosity", "Chasiness", DefaultBounds),
    BallParkTerm("viscosity", "Tragicness", DefaultBounds),
    BallParkTerm("viscosity", "Patheticism", DefaultBounds),
    BallParkTerm("viscosity", "Thwackability", DefaultBounds),
    BallParkTerm("viscosity", "Divinity", DefaultBounds),
    BallParkTerm("viscosity", "Moxie", DefaultBounds),
    BallParkTerm("viscosity", "Musclitude", DefaultBounds),
    BallParkTerm("viscosity", "Martyrdom", DefaultBounds),
    BallParkTerm("viscosity", "Laserlikeness", DefaultBounds),
    BallParkTerm("viscosity", "BaseThirst", DefaultBounds),
    BallParkTerm("viscosity", "Continuation", DefaultBounds),
    BallParkTerm("viscosity", "GroundFriction", DefaultBounds),
    BallParkTerm("viscosity", "Indulgence", DefaultBounds),    
    BallParkTerm("forwardness", "Ruthlessness", DefaultBounds),
    BallParkTerm("forwardness", "Unthwackability", DefaultBounds),
    BallParkTerm("forwardness", "Overpowerment", DefaultBounds),
    BallParkTerm("forwardness", "Shakespearianism", DefaultBounds),
    BallParkTerm("forwardness", "Coldness", DefaultBounds),
    BallParkTerm("forwardness", "Omniscience", DefaultBounds),
    BallParkTerm("forwardness", "Tenaciousness", DefaultBounds),
    BallParkTerm("forwardness", "Watchfulness", DefaultBounds),
    BallParkTerm("forwardness", "Anticapitalism", DefaultBounds),
    BallParkTerm("forwardness", "Chasiness", DefaultBounds),
    BallParkTerm("forwardness", "Tragicness", DefaultBounds),
    BallParkTerm("forwardness", "Patheticism", DefaultBounds),
    BallParkTerm("forwardness", "Thwackability", DefaultBounds),
    BallParkTerm("forwardness", "Divinity", DefaultBounds),
    BallParkTerm("forwardness", "Moxie", DefaultBounds),
    BallParkTerm("forwardness", "Musclitude", DefaultBounds),
    BallParkTerm("forwardness", "Martyrdom", DefaultBounds),
    BallParkTerm("forwardness", "Laserlikeness", DefaultBounds),
    BallParkTerm("forwardness", "BaseThirst", DefaultBounds),
    BallParkTerm("forwardness", "Continuation", DefaultBounds),
    BallParkTerm("forwardness", "GroundFriction", DefaultBounds),
    BallParkTerm("forwardness", "Indulgence", DefaultBounds),    
    BallParkTerm("elongation", "Ruthlessness", DefaultBounds),
    BallParkTerm("elongation", "Unthwackability", DefaultBounds),
    BallParkTerm("elongation", "Overpowerment", DefaultBounds),
    BallParkTerm("elongation", "Shakespearianism", DefaultBounds),
    BallParkTerm("elongation", "Coldness", DefaultBounds),
    BallParkTerm("elongation", "Omniscience", DefaultBounds),
    BallParkTerm("elongation", "Tenaciousness", DefaultBounds),
    BallParkTerm("elongation", "Watchfulness", DefaultBounds),
    BallParkTerm("elongation", "Anticapitalism", DefaultBounds),
    BallParkTerm("elongation", "Chasiness", DefaultBounds),
    BallParkTerm("elongation", "Tragicness", DefaultBounds),
    BallParkTerm("elongation", "Patheticism", DefaultBounds),
    BallParkTerm("elongation", "Thwackability", DefaultBounds),
    BallParkTerm("elongation", "Divinity", DefaultBounds),
    BallParkTerm("elongation", "Moxie", DefaultBounds),
    BallParkTerm("elongation", "Musclitude", DefaultBounds),
    BallParkTerm("elongation", "Martyrdom", DefaultBounds),
    BallParkTerm("elongation", "Laserlikeness", DefaultBounds),
    BallParkTerm("elongation", "BaseThirst", DefaultBounds),
    BallParkTerm("elongation", "Continuation", DefaultBounds),
    BallParkTerm("elongation", "GroundFriction", DefaultBounds),
    BallParkTerm("elongation", "Indulgence", DefaultBounds),    
    BallParkTerm("inconvenience", "Ruthlessness", DefaultBounds),
    BallParkTerm("inconvenience", "Unthwackability", DefaultBounds),
    BallParkTerm("inconvenience", "Overpowerment", DefaultBounds),
    BallParkTerm("inconvenience", "Shakespearianism", DefaultBounds),
    BallParkTerm("inconvenience", "Coldness", DefaultBounds),
    BallParkTerm("inconvenience", "Omniscience", DefaultBounds),
    BallParkTerm("inconvenience", "Tenaciousness", DefaultBounds),
    BallParkTerm("inconvenience", "Watchfulness", DefaultBounds),
    BallParkTerm("inconvenience", "Anticapitalism", DefaultBounds),
    BallParkTerm("inconvenience", "Chasiness", DefaultBounds),
    BallParkTerm("inconvenience", "Tragicness", DefaultBounds),
    BallParkTerm("inconvenience", "Patheticism", DefaultBounds),
    BallParkTerm("inconvenience", "Thwackability", DefaultBounds),
    BallParkTerm("inconvenience", "Divinity", DefaultBounds),
    BallParkTerm("inconvenience", "Moxie", DefaultBounds),
    BallParkTerm("inconvenience", "Musclitude", DefaultBounds),
    BallParkTerm("inconvenience", "Martyrdom", DefaultBounds),
    BallParkTerm("inconvenience", "Laserlikeness", DefaultBounds),
    BallParkTerm("inconvenience", "BaseThirst", DefaultBounds),
    BallParkTerm("inconvenience", "Continuation", DefaultBounds),
    BallParkTerm("inconvenience", "GroundFriction", DefaultBounds),
    BallParkTerm("inconvenience", "Indulgence", DefaultBounds),    
    BallParkTerm("fortification", "Ruthlessness", DefaultBounds),
    BallParkTerm("fortification", "Unthwackability", DefaultBounds),
    BallParkTerm("fortification", "Overpowerment", DefaultBounds),
    BallParkTerm("fortification", "Shakespearianism", DefaultBounds),
    BallParkTerm("fortification", "Coldness", DefaultBounds),
    BallParkTerm("fortification", "Omniscience", DefaultBounds),
    BallParkTerm("fortification", "Tenaciousness", DefaultBounds),
    BallParkTerm("fortification", "Watchfulness", DefaultBounds),
    BallParkTerm("fortification", "Anticapitalism", DefaultBounds),
    BallParkTerm("fortification", "Chasiness", DefaultBounds),
    BallParkTerm("fortification", "Tragicness", DefaultBounds),
    BallParkTerm("fortification", "Patheticism", DefaultBounds),
    BallParkTerm("fortification", "Thwackability", DefaultBounds),
    BallParkTerm("fortification", "Divinity", DefaultBounds),
    BallParkTerm("fortification", "Moxie", DefaultBounds),
    BallParkTerm("fortification", "Musclitude", DefaultBounds),
    BallParkTerm("fortification", "Martyrdom", DefaultBounds),
    BallParkTerm("fortification", "Laserlikeness", DefaultBounds),
    BallParkTerm("fortification", "BaseThirst", DefaultBounds),
    BallParkTerm("fortification", "Continuation", DefaultBounds),
    BallParkTerm("fortification", "GroundFriction", DefaultBounds),
    BallParkTerm("fortification", "Indulgence", DefaultBounds),    
    BallParkTerm("hype", "Ruthlessness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Unthwackability", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Overpowerment", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Shakespearianism", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Coldness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Omniscience", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Tenaciousness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Watchfulness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Anticapitalism", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Chasiness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Tragicness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Patheticism", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Thwackability", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Divinity", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Moxie", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Musclitude", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Martyrdom", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Laserlikeness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "BaseThirst", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Continuation", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "GroundFriction", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Indulgence", [[0, 3], [0, 1], [1, 1.5]])    
]