from collections import namedtuple

BallParkTerm = namedtuple("BallParkTerm", ["ballparkstat", "playerstat", "bounds"])
DefaultBounds = [[-3, 3], [0, 2], [0, 2]]
BuffOnlyBounds = [[0, 3], [0, 2], [0, 2]]
DebuffOnlyBounds = [[-3, 0], [0, 2], [0, 2]]

BALLPARK_TERMS = [                    
    BallParkTerm("grandiosity", "thwack_base_hit", BuffOnlyBounds),
    BallParkTerm("grandiosity", "div_homer", DebuffOnlyBounds),
    BallParkTerm("obtuseness", "thwack_base_hit", BuffOnlyBounds),     
    BallParkTerm("obtuseness", "muscl_foul_ball", DebuffOnlyBounds),        
    BallParkTerm("ominousness", "omni_base_hit", BuffOnlyBounds),        
    BallParkTerm("ominousness", "muscl_triple", DebuffOnlyBounds),    
    BallParkTerm("ominousness", "muscl_double", DebuffOnlyBounds),        
    BallParkTerm("viscosity", "path_connect", DebuffOnlyBounds),    
    BallParkTerm("viscosity", "muscl_triple", DebuffOnlyBounds),    
    BallParkTerm("viscosity", "muscl_double", DebuffOnlyBounds),        
    BallParkTerm("forwardness", "ruth_strike", BuffOnlyBounds),    
    BallParkTerm("forwardness", "muscl_triple", BuffOnlyBounds),
    BallParkTerm("forwardness", "muscl_double", BuffOnlyBounds),    
    BallParkTerm("elongation", "anticap_caught_steal_base", DebuffOnlyBounds),        
    BallParkTerm("elongation", "anticap_caught_steal_home", DebuffOnlyBounds),    
    BallParkTerm("inconvenience", "thwack_base_hit", DebuffOnlyBounds),    
    BallParkTerm("inconvenience", "baset_attempt_steal", DebuffOnlyBounds),    
    BallParkTerm("inconvenience", "laser_attempt_steal", DebuffOnlyBounds),    
    BallParkTerm("fortification", "div_homer", DebuffOnlyBounds),    
    BallParkTerm("hype", "trag_runner_advances", DebuffOnlyBounds),
    BallParkTerm("hype", "path_connect", DebuffOnlyBounds),
    BallParkTerm("hype", "thwack_base_hit", BuffOnlyBounds),
    BallParkTerm("hype", "div_homer", BuffOnlyBounds),
    BallParkTerm("hype", "moxie_swing_correct", BuffOnlyBounds),
    BallParkTerm("hype", "muscl_foul_ball", BuffOnlyBounds),    
    BallParkTerm("hype", "muscl_triple", BuffOnlyBounds),    
    BallParkTerm("hype", "muscl_double", BuffOnlyBounds),    
    BallParkTerm("hype", "martyr_sacrifice", BuffOnlyBounds),
    BallParkTerm("hype", "laser_attempt_steal", BuffOnlyBounds), 
    BallParkTerm("hype", "laser_caught_steal_base", BuffOnlyBounds), 
    BallParkTerm("hype", "laser_caught_steal_home", BuffOnlyBounds), 
    BallParkTerm("hype", "laser_runner_advances", BuffOnlyBounds), 
    BallParkTerm("hype", "baset_attempt_steal", BuffOnlyBounds),    
    BallParkTerm("hype", "baset_caught_steal_home", BuffOnlyBounds),    
    BallParkTerm("hype", "cont_triple", BuffOnlyBounds),    
    BallParkTerm("hype", "cont_double", BuffOnlyBounds),    
    BallParkTerm("hype", "ground_triple", BuffOnlyBounds),    
    BallParkTerm("hype", "indulg_runner_advances", BuffOnlyBounds),        
    BallParkTerm("hype", "unthwack_base_hit", BuffOnlyBounds),
    BallParkTerm("hype", "ruth_strike", BuffOnlyBounds),
    BallParkTerm("hype", "overp_homer", BuffOnlyBounds),    
    BallParkTerm("hype", "overp_triple", BuffOnlyBounds),    
    BallParkTerm("hype", "overp_double", BuffOnlyBounds),    
    BallParkTerm("hype", "shakes_runner_advances", BuffOnlyBounds),    
    #BallParkTerm("hype", "cold_clutch_factor", [[0, 0.1], [0, 0.1], [0, 0.1]]),
    BallParkTerm("hype", "omni_base_hit", BuffOnlyBounds),           
    BallParkTerm("hype", "tenacious_runner_advances", BuffOnlyBounds),    
    BallParkTerm("hype", "watch_attempt_steal", BuffOnlyBounds),    
    BallParkTerm("hype", "anticap_caught_steal_base", BuffOnlyBounds),
    BallParkTerm("hype", "anticap_caught_steal_home", BuffOnlyBounds),
    BallParkTerm("hype", "chasi_triple", BuffOnlyBounds),
    BallParkTerm("hype", "chasi_double", BuffOnlyBounds)    
]