from collections import namedtuple

MofoModTerm = namedtuple("MofoModTerm", ["attr", "team", "stat", "bounds"])

MOFO_MOD_TERMS = [    
    MofoModTerm("LOVE", "opp", "Ruthlessness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "Unthwackability", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "Overpowerment", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "Shakespearianism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "Coldness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanTragicness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanPatheticism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanLaserlikeness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MeanIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxLaserLikeness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("LOVE", "opp", "MaxIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "Ruthlessness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "Unthwackability", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "Overpowerment", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "Shakespearianism", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "Coldness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MeanOmniscience", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MeanTenaciousness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MeanWatchfulness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MeanAnticapitalism", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MeanChasiness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanTragicness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanPatheticism", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanThwackability", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanDivinity", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanMoxie", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanMusclitude", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanMartyrdom", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanLaserlikeness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanBaseThirst", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanContinuation", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanGroundFriction", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanIndulgence", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MaxOmniscience", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MaxTenaciousness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MaxWatchfulness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MaxAnticapitalism", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MaxChasiness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxThwackability", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxDivinity", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxMoxie", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxMusclitude", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxMartyrdom", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxLaserLikeness", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxBaseThirst", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxContinuation", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxGroundFriction", [[-15, 10], [-3, 4], [-3, 4]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxIndulgence", [[-15, 10], [-3, 4], [-3, 4]]),    
    MofoModTerm("O_NO", "opp", "Ruthlessness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "Unthwackability", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "Overpowerment", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "Shakespearianism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "Coldness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "MeanOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "MeanTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "MeanWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "MeanAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "MeanChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanTragicness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanPatheticism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanLaserlikeness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MeanIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "MaxOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "MaxTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "MaxWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "MaxAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "opp", "MaxChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MaxThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MaxDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MaxMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MaxMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MaxMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MaxLaserLikeness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MaxBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MaxContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MaxGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("O_NO", "same", "MaxIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "Ruthlessness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "Unthwackability", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "Overpowerment", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "Shakespearianism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "Coldness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MeanOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MeanTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MeanWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MeanAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MeanChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanTragicness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanPatheticism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanLaserlikeness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MaxOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MaxTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MaxWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MaxAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MaxChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxLaserLikeness", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxIndulgence", [[-10, 10], [-3, 3], [-3, 3]])
]

#MOFO_MOD_TERMS = [
#    MofoModTerm("EXTRA_BASE", "opp", "Ruthlessness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "Unthwackability", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "Overpowerment", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "Shakespearianism", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "Coldness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MeanOmniscience", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MeanTenaciousness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MeanWatchfulness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MeanAnticapitalism", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MeanChasiness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanTragicness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanPatheticism", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanThwackability", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanDivinity", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanMoxie", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanMusclitude", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanMartyrdom", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanLaserlikeness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanBaseThirst", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanContinuation", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanGroundFriction", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanIndulgence", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MaxOmniscience", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MaxTenaciousness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MaxWatchfulness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MaxAnticapitalism", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MaxChasiness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxThwackability", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxDivinity", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxMoxie", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxMusclitude", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxMartyrdom", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxLaserLikeness", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxBaseThirst", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxContinuation", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxGroundFriction", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxIndulgence", [[-15, 15], [-4, 3], [-4, 3]]),
#    MofoModTerm("LOVE", "opp", "Ruthlessness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "Unthwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "Overpowerment", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "Shakespearianism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "Coldness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanTragicness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanPatheticism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanLaserlikeness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MeanIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxLaserLikeness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("LOVE", "opp", "MaxIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "Ruthlessness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "Unthwackability", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "Overpowerment", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "Shakespearianism", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "Coldness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MeanOmniscience", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MeanTenaciousness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MeanWatchfulness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MeanAnticapitalism", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MeanChasiness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanTragicness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanPatheticism", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanThwackability", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanDivinity", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanMoxie", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanMusclitude", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanMartyrdom", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanLaserlikeness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanBaseThirst", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanContinuation", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanGroundFriction", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanIndulgence", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MaxOmniscience", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MaxTenaciousness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MaxWatchfulness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MaxAnticapitalism", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MaxChasiness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxThwackability", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxDivinity", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxMoxie", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxMusclitude", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxMartyrdom", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxLaserLikeness", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxBaseThirst", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxContinuation", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxGroundFriction", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxIndulgence", [[-15, 10], [-3, 4], [-3, 4]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "Ruthlessness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "Unthwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "Overpowerment", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "Shakespearianism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "Coldness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MeanOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MeanTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MeanWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MeanAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MeanChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanTragicness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanPatheticism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanLaserlikeness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MaxOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MaxTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MaxWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MaxAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MaxChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxLaserLikeness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "Ruthlessness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "Unthwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "Overpowerment", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "Shakespearianism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "Coldness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "MeanOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "MeanTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "MeanWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "MeanAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "MeanChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanTragicness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanPatheticism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanLaserlikeness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MeanIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "MaxOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "MaxTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "MaxWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "MaxAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "opp", "MaxChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MaxThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MaxDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MaxMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MaxMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MaxMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MaxLaserLikeness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MaxBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MaxContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MaxGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("O_NO", "same", "MaxIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "Ruthlessness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "Unthwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "Overpowerment", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "Shakespearianism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "Coldness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MeanOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MeanTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MeanWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MeanAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MeanChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanTragicness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanPatheticism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanLaserlikeness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanIndulgence", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MaxOmniscience", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MaxTenaciousness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MaxWatchfulness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MaxAnticapitalism", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MaxChasiness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxThwackability", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxDivinity", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxMoxie", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxMusclitude", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxMartyrdom", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxLaserLikeness", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxBaseThirst", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxContinuation", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxGroundFriction", [[-10, 10], [-3, 3], [-3, 3]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxIndulgence", [[-10, 10], [-3, 3], [-3, 3]])
#]
