from collections import namedtuple

BallParkTerm = namedtuple("BallParkTerm", ["ballparkstat", "playerstat", "bounds"])
DefaultBounds = [[-3, 3], [0, 1], [1, 1.5]]

BALLPARK_TERMS = [    
    BallParkTerm("grandiosity", "Ruthlessness", DefaultBounds),
    BallParkTerm("grandiosity", "Unthwackability", DefaultBounds),
    BallParkTerm("grandiosity", "Overpowerment", DefaultBounds),
    BallParkTerm("grandiosity", "Shakespearianism", DefaultBounds),
    BallParkTerm("grandiosity", "Coldness", DefaultBounds),
    BallParkTerm("grandiosity", "MeanOmniscience", DefaultBounds),
    BallParkTerm("grandiosity", "MeanTenaciousness", DefaultBounds),
    BallParkTerm("grandiosity", "MeanWatchfulness", DefaultBounds),
    BallParkTerm("grandiosity", "MeanAnticapitalism", DefaultBounds),
    BallParkTerm("grandiosity", "MeanChasiness", DefaultBounds),
    BallParkTerm("grandiosity", "MeanTragicness", DefaultBounds),
    BallParkTerm("grandiosity", "MeanPatheticism", DefaultBounds),
    BallParkTerm("grandiosity", "MeanThwackability", DefaultBounds),
    BallParkTerm("grandiosity", "MeanDivinity", DefaultBounds),
    BallParkTerm("grandiosity", "MeanMoxie", DefaultBounds),
    BallParkTerm("grandiosity", "MeanMusclitude", DefaultBounds),
    BallParkTerm("grandiosity", "MeanMartyrdom", DefaultBounds),
    BallParkTerm("grandiosity", "MeanLaserlikeness", DefaultBounds),
    BallParkTerm("grandiosity", "MeanBaseThirst", DefaultBounds),
    BallParkTerm("grandiosity", "MeanContinuation", DefaultBounds),
    BallParkTerm("grandiosity", "MeanGroundFriction", DefaultBounds),
    BallParkTerm("grandiosity", "MeanIndulgence", DefaultBounds),
    BallParkTerm("grandiosity", "MaxOmniscience", DefaultBounds),
    BallParkTerm("grandiosity", "MaxTenaciousness", DefaultBounds),
    BallParkTerm("grandiosity", "MaxWatchfulness", DefaultBounds),
    BallParkTerm("grandiosity", "MaxAnticapitalism", DefaultBounds),
    BallParkTerm("grandiosity", "MaxChasiness", DefaultBounds),
    BallParkTerm("grandiosity", "MaxThwackability", DefaultBounds),
    BallParkTerm("grandiosity", "MaxDivinity", DefaultBounds),
    BallParkTerm("grandiosity", "MaxMoxie", DefaultBounds),
    BallParkTerm("grandiosity", "MaxMusclitude", DefaultBounds),
    BallParkTerm("grandiosity", "MaxMartyrdom", DefaultBounds),
    BallParkTerm("grandiosity", "MaxLaserLikeness", DefaultBounds),
    BallParkTerm("grandiosity", "MaxBaseThirst", DefaultBounds),
    BallParkTerm("grandiosity", "MaxContinuation", DefaultBounds),
    BallParkTerm("grandiosity", "MaxGroundFriction", DefaultBounds),
    BallParkTerm("grandiosity", "MaxIndulgence", DefaultBounds),    
    BallParkTerm("obtuseness", "Ruthlessness", DefaultBounds),
    BallParkTerm("obtuseness", "Unthwackability", DefaultBounds),
    BallParkTerm("obtuseness", "Overpowerment", DefaultBounds),
    BallParkTerm("obtuseness", "Shakespearianism", DefaultBounds),
    BallParkTerm("obtuseness", "Coldness", DefaultBounds),
    BallParkTerm("obtuseness", "MeanOmniscience", DefaultBounds),
    BallParkTerm("obtuseness", "MeanTenaciousness", DefaultBounds),
    BallParkTerm("obtuseness", "MeanWatchfulness", DefaultBounds),
    BallParkTerm("obtuseness", "MeanAnticapitalism", DefaultBounds),
    BallParkTerm("obtuseness", "MeanChasiness", DefaultBounds),
    BallParkTerm("obtuseness", "MeanTragicness", DefaultBounds),
    BallParkTerm("obtuseness", "MeanPatheticism", DefaultBounds),
    BallParkTerm("obtuseness", "MeanThwackability", DefaultBounds),
    BallParkTerm("obtuseness", "MeanDivinity", DefaultBounds),
    BallParkTerm("obtuseness", "MeanMoxie", DefaultBounds),
    BallParkTerm("obtuseness", "MeanMusclitude", DefaultBounds),
    BallParkTerm("obtuseness", "MeanMartyrdom", DefaultBounds),
    BallParkTerm("obtuseness", "MeanLaserlikeness", DefaultBounds),
    BallParkTerm("obtuseness", "MeanBaseThirst", DefaultBounds),
    BallParkTerm("obtuseness", "MeanContinuation", DefaultBounds),
    BallParkTerm("obtuseness", "MeanGroundFriction", DefaultBounds),
    BallParkTerm("obtuseness", "MeanIndulgence", DefaultBounds),
    BallParkTerm("obtuseness", "MaxOmniscience", DefaultBounds),
    BallParkTerm("obtuseness", "MaxTenaciousness", DefaultBounds),
    BallParkTerm("obtuseness", "MaxWatchfulness", DefaultBounds),
    BallParkTerm("obtuseness", "MaxAnticapitalism", DefaultBounds),
    BallParkTerm("obtuseness", "MaxChasiness", DefaultBounds),
    BallParkTerm("obtuseness", "MaxThwackability", DefaultBounds),
    BallParkTerm("obtuseness", "MaxDivinity", DefaultBounds),
    BallParkTerm("obtuseness", "MaxMoxie", DefaultBounds),
    BallParkTerm("obtuseness", "MaxMusclitude", DefaultBounds),
    BallParkTerm("obtuseness", "MaxMartyrdom", DefaultBounds),
    BallParkTerm("obtuseness", "MaxLaserLikeness", DefaultBounds),
    BallParkTerm("obtuseness", "MaxBaseThirst", DefaultBounds),
    BallParkTerm("obtuseness", "MaxContinuation", DefaultBounds),
    BallParkTerm("obtuseness", "MaxGroundFriction", DefaultBounds),
    BallParkTerm("obtuseness", "MaxIndulgence", DefaultBounds),
    BallParkTerm("ominousness", "Ruthlessness", DefaultBounds),
    BallParkTerm("ominousness", "Unthwackability", DefaultBounds),
    BallParkTerm("ominousness", "Overpowerment", DefaultBounds),
    BallParkTerm("ominousness", "Shakespearianism", DefaultBounds),
    BallParkTerm("ominousness", "Coldness", DefaultBounds),
    BallParkTerm("ominousness", "MeanOmniscience", DefaultBounds),
    BallParkTerm("ominousness", "MeanTenaciousness", DefaultBounds),
    BallParkTerm("ominousness", "MeanWatchfulness", DefaultBounds),
    BallParkTerm("ominousness", "MeanAnticapitalism", DefaultBounds),
    BallParkTerm("ominousness", "MeanChasiness", DefaultBounds),
    BallParkTerm("ominousness", "MeanTragicness", DefaultBounds),
    BallParkTerm("ominousness", "MeanPatheticism", DefaultBounds),
    BallParkTerm("ominousness", "MeanThwackability", DefaultBounds),
    BallParkTerm("ominousness", "MeanDivinity", DefaultBounds),
    BallParkTerm("ominousness", "MeanMoxie", DefaultBounds),
    BallParkTerm("ominousness", "MeanMusclitude", DefaultBounds),
    BallParkTerm("ominousness", "MeanMartyrdom", DefaultBounds),
    BallParkTerm("ominousness", "MeanLaserlikeness", DefaultBounds),
    BallParkTerm("ominousness", "MeanBaseThirst", DefaultBounds),
    BallParkTerm("ominousness", "MeanContinuation", DefaultBounds),
    BallParkTerm("ominousness", "MeanGroundFriction", DefaultBounds),
    BallParkTerm("ominousness", "MeanIndulgence", DefaultBounds),
    BallParkTerm("ominousness", "MaxOmniscience", DefaultBounds),
    BallParkTerm("ominousness", "MaxTenaciousness", DefaultBounds),
    BallParkTerm("ominousness", "MaxWatchfulness", DefaultBounds),
    BallParkTerm("ominousness", "MaxAnticapitalism", DefaultBounds),
    BallParkTerm("ominousness", "MaxChasiness", DefaultBounds),
    BallParkTerm("ominousness", "MaxThwackability", DefaultBounds),
    BallParkTerm("ominousness", "MaxDivinity", DefaultBounds),
    BallParkTerm("ominousness", "MaxMoxie", DefaultBounds),
    BallParkTerm("ominousness", "MaxMusclitude", DefaultBounds),
    BallParkTerm("ominousness", "MaxMartyrdom", DefaultBounds),
    BallParkTerm("ominousness", "MaxLaserLikeness", DefaultBounds),
    BallParkTerm("ominousness", "MaxBaseThirst", DefaultBounds),
    BallParkTerm("ominousness", "MaxContinuation", DefaultBounds),
    BallParkTerm("ominousness", "MaxGroundFriction", DefaultBounds),
    BallParkTerm("ominousness", "MaxIndulgence", DefaultBounds),
    BallParkTerm("viscosity", "Ruthlessness", DefaultBounds),
    BallParkTerm("viscosity", "Unthwackability", DefaultBounds),
    BallParkTerm("viscosity", "Overpowerment", DefaultBounds),
    BallParkTerm("viscosity", "Shakespearianism", DefaultBounds),
    BallParkTerm("viscosity", "Coldness", DefaultBounds),
    BallParkTerm("viscosity", "MeanOmniscience", DefaultBounds),
    BallParkTerm("viscosity", "MeanTenaciousness", DefaultBounds),
    BallParkTerm("viscosity", "MeanWatchfulness", DefaultBounds),
    BallParkTerm("viscosity", "MeanAnticapitalism", DefaultBounds),
    BallParkTerm("viscosity", "MeanChasiness", DefaultBounds),
    BallParkTerm("viscosity", "MeanTragicness", DefaultBounds),
    BallParkTerm("viscosity", "MeanPatheticism", DefaultBounds),
    BallParkTerm("viscosity", "MeanThwackability", DefaultBounds),
    BallParkTerm("viscosity", "MeanDivinity", DefaultBounds),
    BallParkTerm("viscosity", "MeanMoxie", DefaultBounds),
    BallParkTerm("viscosity", "MeanMusclitude", DefaultBounds),
    BallParkTerm("viscosity", "MeanMartyrdom", DefaultBounds),
    BallParkTerm("viscosity", "MeanLaserlikeness", DefaultBounds),
    BallParkTerm("viscosity", "MeanBaseThirst", DefaultBounds),
    BallParkTerm("viscosity", "MeanContinuation", DefaultBounds),
    BallParkTerm("viscosity", "MeanGroundFriction", DefaultBounds),
    BallParkTerm("viscosity", "MeanIndulgence", DefaultBounds),
    BallParkTerm("viscosity", "MaxOmniscience", DefaultBounds),
    BallParkTerm("viscosity", "MaxTenaciousness", DefaultBounds),
    BallParkTerm("viscosity", "MaxWatchfulness", DefaultBounds),
    BallParkTerm("viscosity", "MaxAnticapitalism", DefaultBounds),
    BallParkTerm("viscosity", "MaxChasiness", DefaultBounds),
    BallParkTerm("viscosity", "MaxThwackability", DefaultBounds),
    BallParkTerm("viscosity", "MaxDivinity", DefaultBounds),
    BallParkTerm("viscosity", "MaxMoxie", DefaultBounds),
    BallParkTerm("viscosity", "MaxMusclitude", DefaultBounds),
    BallParkTerm("viscosity", "MaxMartyrdom", DefaultBounds),
    BallParkTerm("viscosity", "MaxLaserLikeness", DefaultBounds),
    BallParkTerm("viscosity", "MaxBaseThirst", DefaultBounds),
    BallParkTerm("viscosity", "MaxContinuation", DefaultBounds),
    BallParkTerm("viscosity", "MaxGroundFriction", DefaultBounds),
    BallParkTerm("viscosity", "MaxIndulgence", DefaultBounds),
    BallParkTerm("forwardness", "Ruthlessness", DefaultBounds),
    BallParkTerm("forwardness", "Unthwackability", DefaultBounds),
    BallParkTerm("forwardness", "Overpowerment", DefaultBounds),
    BallParkTerm("forwardness", "Shakespearianism", DefaultBounds),
    BallParkTerm("forwardness", "Coldness", DefaultBounds),
    BallParkTerm("forwardness", "MeanOmniscience", DefaultBounds),
    BallParkTerm("forwardness", "MeanTenaciousness", DefaultBounds),
    BallParkTerm("forwardness", "MeanWatchfulness", DefaultBounds),
    BallParkTerm("forwardness", "MeanAnticapitalism", DefaultBounds),
    BallParkTerm("forwardness", "MeanChasiness", DefaultBounds),
    BallParkTerm("forwardness", "MeanTragicness", DefaultBounds),
    BallParkTerm("forwardness", "MeanPatheticism", DefaultBounds),
    BallParkTerm("forwardness", "MeanThwackability", DefaultBounds),
    BallParkTerm("forwardness", "MeanDivinity", DefaultBounds),
    BallParkTerm("forwardness", "MeanMoxie", DefaultBounds),
    BallParkTerm("forwardness", "MeanMusclitude", DefaultBounds),
    BallParkTerm("forwardness", "MeanMartyrdom", DefaultBounds),
    BallParkTerm("forwardness", "MeanLaserlikeness", DefaultBounds),
    BallParkTerm("forwardness", "MeanBaseThirst", DefaultBounds),
    BallParkTerm("forwardness", "MeanContinuation", DefaultBounds),
    BallParkTerm("forwardness", "MeanGroundFriction", DefaultBounds),
    BallParkTerm("forwardness", "MeanIndulgence", DefaultBounds),
    BallParkTerm("forwardness", "MaxOmniscience", DefaultBounds),
    BallParkTerm("forwardness", "MaxTenaciousness", DefaultBounds),
    BallParkTerm("forwardness", "MaxWatchfulness", DefaultBounds),
    BallParkTerm("forwardness", "MaxAnticapitalism", DefaultBounds),
    BallParkTerm("forwardness", "MaxChasiness", DefaultBounds),
    BallParkTerm("forwardness", "MaxThwackability", DefaultBounds),
    BallParkTerm("forwardness", "MaxDivinity", DefaultBounds),
    BallParkTerm("forwardness", "MaxMoxie", DefaultBounds),
    BallParkTerm("forwardness", "MaxMusclitude", DefaultBounds),
    BallParkTerm("forwardness", "MaxMartyrdom", DefaultBounds),
    BallParkTerm("forwardness", "MaxLaserLikeness", DefaultBounds),
    BallParkTerm("forwardness", "MaxBaseThirst", DefaultBounds),
    BallParkTerm("forwardness", "MaxContinuation", DefaultBounds),
    BallParkTerm("forwardness", "MaxGroundFriction", DefaultBounds),
    BallParkTerm("forwardness", "MaxIndulgence", DefaultBounds),
    BallParkTerm("elongation", "Ruthlessness", DefaultBounds),
    BallParkTerm("elongation", "Unthwackability", DefaultBounds),
    BallParkTerm("elongation", "Overpowerment", DefaultBounds),
    BallParkTerm("elongation", "Shakespearianism", DefaultBounds),
    BallParkTerm("elongation", "Coldness", DefaultBounds),
    BallParkTerm("elongation", "MeanOmniscience", DefaultBounds),
    BallParkTerm("elongation", "MeanTenaciousness", DefaultBounds),
    BallParkTerm("elongation", "MeanWatchfulness", DefaultBounds),
    BallParkTerm("elongation", "MeanAnticapitalism", DefaultBounds),
    BallParkTerm("elongation", "MeanChasiness", DefaultBounds),
    BallParkTerm("elongation", "MeanTragicness", DefaultBounds),
    BallParkTerm("elongation", "MeanPatheticism", DefaultBounds),
    BallParkTerm("elongation", "MeanThwackability", DefaultBounds),
    BallParkTerm("elongation", "MeanDivinity", DefaultBounds),
    BallParkTerm("elongation", "MeanMoxie", DefaultBounds),
    BallParkTerm("elongation", "MeanMusclitude", DefaultBounds),
    BallParkTerm("elongation", "MeanMartyrdom", DefaultBounds),
    BallParkTerm("elongation", "MeanLaserlikeness", DefaultBounds),
    BallParkTerm("elongation", "MeanBaseThirst", DefaultBounds),
    BallParkTerm("elongation", "MeanContinuation", DefaultBounds),
    BallParkTerm("elongation", "MeanGroundFriction", DefaultBounds),
    BallParkTerm("elongation", "MeanIndulgence", DefaultBounds),
    BallParkTerm("elongation", "MaxOmniscience", DefaultBounds),
    BallParkTerm("elongation", "MaxTenaciousness", DefaultBounds),
    BallParkTerm("elongation", "MaxWatchfulness", DefaultBounds),
    BallParkTerm("elongation", "MaxAnticapitalism", DefaultBounds),
    BallParkTerm("elongation", "MaxChasiness", DefaultBounds),
    BallParkTerm("elongation", "MaxThwackability", DefaultBounds),
    BallParkTerm("elongation", "MaxDivinity", DefaultBounds),
    BallParkTerm("elongation", "MaxMoxie", DefaultBounds),
    BallParkTerm("elongation", "MaxMusclitude", DefaultBounds),
    BallParkTerm("elongation", "MaxMartyrdom", DefaultBounds),
    BallParkTerm("elongation", "MaxLaserLikeness", DefaultBounds),
    BallParkTerm("elongation", "MaxBaseThirst", DefaultBounds),
    BallParkTerm("elongation", "MaxContinuation", DefaultBounds),
    BallParkTerm("elongation", "MaxGroundFriction", DefaultBounds),
    BallParkTerm("elongation", "MaxIndulgence", DefaultBounds),
    BallParkTerm("inconvenience", "Ruthlessness", DefaultBounds),
    BallParkTerm("inconvenience", "Unthwackability", DefaultBounds),
    BallParkTerm("inconvenience", "Overpowerment", DefaultBounds),
    BallParkTerm("inconvenience", "Shakespearianism", DefaultBounds),
    BallParkTerm("inconvenience", "Coldness", DefaultBounds),
    BallParkTerm("inconvenience", "MeanOmniscience", DefaultBounds),
    BallParkTerm("inconvenience", "MeanTenaciousness", DefaultBounds),
    BallParkTerm("inconvenience", "MeanWatchfulness", DefaultBounds),
    BallParkTerm("inconvenience", "MeanAnticapitalism", DefaultBounds),
    BallParkTerm("inconvenience", "MeanChasiness", DefaultBounds),
    BallParkTerm("inconvenience", "MeanTragicness", DefaultBounds),
    BallParkTerm("inconvenience", "MeanPatheticism", DefaultBounds),
    BallParkTerm("inconvenience", "MeanThwackability", DefaultBounds),
    BallParkTerm("inconvenience", "MeanDivinity", DefaultBounds),
    BallParkTerm("inconvenience", "MeanMoxie", DefaultBounds),
    BallParkTerm("inconvenience", "MeanMusclitude", DefaultBounds),
    BallParkTerm("inconvenience", "MeanMartyrdom", DefaultBounds),
    BallParkTerm("inconvenience", "MeanLaserlikeness", DefaultBounds),
    BallParkTerm("inconvenience", "MeanBaseThirst", DefaultBounds),
    BallParkTerm("inconvenience", "MeanContinuation", DefaultBounds),
    BallParkTerm("inconvenience", "MeanGroundFriction", DefaultBounds),
    BallParkTerm("inconvenience", "MeanIndulgence", DefaultBounds),
    BallParkTerm("inconvenience", "MaxOmniscience", DefaultBounds),
    BallParkTerm("inconvenience", "MaxTenaciousness", DefaultBounds),
    BallParkTerm("inconvenience", "MaxWatchfulness", DefaultBounds),
    BallParkTerm("inconvenience", "MaxAnticapitalism", DefaultBounds),
    BallParkTerm("inconvenience", "MaxChasiness", DefaultBounds),
    BallParkTerm("inconvenience", "MaxThwackability", DefaultBounds),
    BallParkTerm("inconvenience", "MaxDivinity", DefaultBounds),
    BallParkTerm("inconvenience", "MaxMoxie", DefaultBounds),
    BallParkTerm("inconvenience", "MaxMusclitude", DefaultBounds),
    BallParkTerm("inconvenience", "MaxMartyrdom", DefaultBounds),
    BallParkTerm("inconvenience", "MaxLaserLikeness", DefaultBounds),
    BallParkTerm("inconvenience", "MaxBaseThirst", DefaultBounds),
    BallParkTerm("inconvenience", "MaxContinuation", DefaultBounds),
    BallParkTerm("inconvenience", "MaxGroundFriction", DefaultBounds),
    BallParkTerm("inconvenience", "MaxIndulgence", DefaultBounds),
    BallParkTerm("fortification", "Ruthlessness", DefaultBounds),
    BallParkTerm("fortification", "Unthwackability", DefaultBounds),
    BallParkTerm("fortification", "Overpowerment", DefaultBounds),
    BallParkTerm("fortification", "Shakespearianism", DefaultBounds),
    BallParkTerm("fortification", "Coldness", DefaultBounds),
    BallParkTerm("fortification", "MeanOmniscience", DefaultBounds),
    BallParkTerm("fortification", "MeanTenaciousness", DefaultBounds),
    BallParkTerm("fortification", "MeanWatchfulness", DefaultBounds),
    BallParkTerm("fortification", "MeanAnticapitalism", DefaultBounds),
    BallParkTerm("fortification", "MeanChasiness", DefaultBounds),
    BallParkTerm("fortification", "MeanTragicness", DefaultBounds),
    BallParkTerm("fortification", "MeanPatheticism", DefaultBounds),
    BallParkTerm("fortification", "MeanThwackability", DefaultBounds),
    BallParkTerm("fortification", "MeanDivinity", DefaultBounds),
    BallParkTerm("fortification", "MeanMoxie", DefaultBounds),
    BallParkTerm("fortification", "MeanMusclitude", DefaultBounds),
    BallParkTerm("fortification", "MeanMartyrdom", DefaultBounds),
    BallParkTerm("fortification", "MeanLaserlikeness", DefaultBounds),
    BallParkTerm("fortification", "MeanBaseThirst", DefaultBounds),
    BallParkTerm("fortification", "MeanContinuation", DefaultBounds),
    BallParkTerm("fortification", "MeanGroundFriction", DefaultBounds),
    BallParkTerm("fortification", "MeanIndulgence", DefaultBounds),
    BallParkTerm("fortification", "MaxOmniscience", DefaultBounds),
    BallParkTerm("fortification", "MaxTenaciousness", DefaultBounds),
    BallParkTerm("fortification", "MaxWatchfulness", DefaultBounds),
    BallParkTerm("fortification", "MaxAnticapitalism", DefaultBounds),
    BallParkTerm("fortification", "MaxChasiness", DefaultBounds),
    BallParkTerm("fortification", "MaxThwackability", DefaultBounds),
    BallParkTerm("fortification", "MaxDivinity", DefaultBounds),
    BallParkTerm("fortification", "MaxMoxie", DefaultBounds),
    BallParkTerm("fortification", "MaxMusclitude", DefaultBounds),
    BallParkTerm("fortification", "MaxMartyrdom", DefaultBounds),
    BallParkTerm("fortification", "MaxLaserLikeness", DefaultBounds),
    BallParkTerm("fortification", "MaxBaseThirst", DefaultBounds),
    BallParkTerm("fortification", "MaxContinuation", DefaultBounds),
    BallParkTerm("fortification", "MaxGroundFriction", DefaultBounds),
    BallParkTerm("fortification", "MaxIndulgence", DefaultBounds),
    BallParkTerm("hype", "Ruthlessness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Unthwackability", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Overpowerment", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Shakespearianism", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "Coldness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanOmniscience", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanTenaciousness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanWatchfulness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanAnticapitalism", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanChasiness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanTragicness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanPatheticism", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanThwackability", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanDivinity", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanMoxie", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanMusclitude", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanMartyrdom", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanLaserlikeness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanBaseThirst", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanContinuation", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanGroundFriction", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MeanIndulgence", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxOmniscience", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxTenaciousness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxWatchfulness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxAnticapitalism", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxChasiness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxThwackability", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxDivinity", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxMoxie", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxMusclitude", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxMartyrdom", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxLaserLikeness", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxBaseThirst", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxContinuation", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxGroundFriction", [[0, 3], [0, 1], [1, 1.5]]),
    BallParkTerm("hype", "MaxIndulgence", [[0, 3], [0, 1], [1, 1.5]])
]