from collections import namedtuple

MofoModTerm = namedtuple("MofoModTerm", ["attr", "team", "stat", "bounds"])

MOFO_MOD_TERMS = [    
    MofoModTerm("LOVE", "opp", "Ruthlessness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "Unthwackability", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "Overpowerment", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "Shakespearianism", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "Coldness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanOmniscience", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanTenaciousness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanWatchfulness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanAnticapitalism", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanChasiness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanTragicness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanPatheticism", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanThwackability", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanDivinity", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanMoxie", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanMusclitude", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanMartyrdom", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanLaserlikeness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanBaseThirst", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanContinuation", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanGroundFriction", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MeanIndulgence", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxOmniscience", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxTenaciousness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxWatchfulness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxAnticapitalism", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxChasiness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxThwackability", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxDivinity", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxMoxie", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxMusclitude", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxMartyrdom", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxLaserLikeness", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxBaseThirst", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxContinuation", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxGroundFriction", [[-2, 2]]),
    MofoModTerm("LOVE", "opp", "MaxIndulgence", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "Ruthlessness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "Unthwackability", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "Overpowerment", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "Shakespearianism", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "Coldness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MeanOmniscience", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MeanTenaciousness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MeanWatchfulness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MeanAnticapitalism", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MeanChasiness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanTragicness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanPatheticism", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanThwackability", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanDivinity", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanMoxie", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanMusclitude", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanMartyrdom", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanLaserlikeness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanBaseThirst", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanContinuation", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanGroundFriction", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MeanIndulgence", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MaxOmniscience", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MaxTenaciousness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MaxWatchfulness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MaxAnticapitalism", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "opp", "MaxChasiness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxThwackability", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxDivinity", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxMoxie", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxMusclitude", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxMartyrdom", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxLaserLikeness", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxBaseThirst", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxContinuation", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxGroundFriction", [[-2, 2]]),
    MofoModTerm("EXTRA_STRIKE", "same", "MaxIndulgence", [[-2, 2]]),    
    MofoModTerm("O_NO", "opp", "Ruthlessness", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "Unthwackability", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "Overpowerment", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "Shakespearianism", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "Coldness", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "MeanOmniscience", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "MeanTenaciousness", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "MeanWatchfulness", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "MeanAnticapitalism", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "MeanChasiness", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanTragicness", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanPatheticism", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanThwackability", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanDivinity", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanMoxie", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanMusclitude", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanMartyrdom", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanLaserlikeness", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanBaseThirst", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanContinuation", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanGroundFriction", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MeanIndulgence", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "MaxOmniscience", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "MaxTenaciousness", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "MaxWatchfulness", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "MaxAnticapitalism", [[-2, 2]]),
    MofoModTerm("O_NO", "opp", "MaxChasiness", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MaxThwackability", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MaxDivinity", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MaxMoxie", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MaxMusclitude", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MaxMartyrdom", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MaxLaserLikeness", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MaxBaseThirst", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MaxContinuation", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MaxGroundFriction", [[-2, 2]]),
    MofoModTerm("O_NO", "same", "MaxIndulgence", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "Ruthlessness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "Unthwackability", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "Overpowerment", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "Shakespearianism", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "Coldness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MeanOmniscience", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MeanTenaciousness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MeanWatchfulness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MeanAnticapitalism", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MeanChasiness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanTragicness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanPatheticism", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanThwackability", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanDivinity", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanMoxie", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanMusclitude", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanMartyrdom", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanLaserlikeness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanBaseThirst", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanContinuation", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanGroundFriction", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MeanIndulgence", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MaxOmniscience", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MaxTenaciousness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MaxWatchfulness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MaxAnticapitalism", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "opp", "MaxChasiness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxThwackability", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxDivinity", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxMoxie", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxMusclitude", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxMartyrdom", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxLaserLikeness", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxBaseThirst", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxContinuation", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxGroundFriction", [[-2, 2]]),
    MofoModTerm("BASE_INSTINCTS", "same", "MaxIndulgence", [[-2, 2]])
]

#MOFO_MOD_TERMS = [
#    MofoModTerm("EXTRA_BASE", "opp", "Ruthlessness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "Unthwackability", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "Overpowerment", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "Shakespearianism", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "Coldness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MeanOmniscience", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MeanTenaciousness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MeanWatchfulness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MeanAnticapitalism", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MeanChasiness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanTragicness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanPatheticism", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanThwackability", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanDivinity", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanMoxie", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanMusclitude", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanMartyrdom", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanLaserlikeness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanBaseThirst", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanContinuation", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanGroundFriction", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MeanIndulgence", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MaxOmniscience", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MaxTenaciousness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MaxWatchfulness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MaxAnticapitalism", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "opp", "MaxChasiness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxThwackability", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxDivinity", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxMoxie", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxMusclitude", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxMartyrdom", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxLaserLikeness", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxBaseThirst", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxContinuation", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxGroundFriction", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("EXTRA_BASE", "same", "MaxIndulgence", [[0, 15], [-4, 0], [-4, 0]]),
#    MofoModTerm("LOVE", "opp", "Ruthlessness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "Unthwackability", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "Overpowerment", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "Shakespearianism", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "Coldness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanOmniscience", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanTenaciousness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanWatchfulness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanAnticapitalism", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanChasiness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanTragicness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanPatheticism", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanThwackability", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanDivinity", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanMoxie", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanMusclitude", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanMartyrdom", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanLaserlikeness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanBaseThirst", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanContinuation", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanGroundFriction", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MeanIndulgence", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxOmniscience", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxTenaciousness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxWatchfulness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxAnticapitalism", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxChasiness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxThwackability", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxDivinity", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxMoxie", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxMusclitude", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxMartyrdom", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxLaserLikeness", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxBaseThirst", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxContinuation", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxGroundFriction", [[-2, 2]]),
#    MofoModTerm("LOVE", "opp", "MaxIndulgence", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "Ruthlessness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "Unthwackability", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "Overpowerment", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "Shakespearianism", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "Coldness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MeanOmniscience", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MeanTenaciousness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MeanWatchfulness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MeanAnticapitalism", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MeanChasiness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanTragicness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanPatheticism", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanThwackability", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanDivinity", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanMoxie", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanMusclitude", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanMartyrdom", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanLaserlikeness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanBaseThirst", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanContinuation", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanGroundFriction", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MeanIndulgence", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MaxOmniscience", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MaxTenaciousness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MaxWatchfulness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MaxAnticapitalism", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "opp", "MaxChasiness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxThwackability", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxDivinity", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxMoxie", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxMusclitude", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxMartyrdom", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxLaserLikeness", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxBaseThirst", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxContinuation", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxGroundFriction", [[-2, 2]]),
#    MofoModTerm("EXTRA_STRIKE", "same", "MaxIndulgence", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "Ruthlessness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "Unthwackability", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "Overpowerment", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "Shakespearianism", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "Coldness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MeanOmniscience", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MeanTenaciousness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MeanWatchfulness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MeanAnticapitalism", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MeanChasiness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanTragicness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanPatheticism", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanThwackability", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanDivinity", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanMoxie", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanMusclitude", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanMartyrdom", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanLaserlikeness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanBaseThirst", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanContinuation", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanGroundFriction", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MeanIndulgence", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MaxOmniscience", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MaxTenaciousness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MaxWatchfulness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MaxAnticapitalism", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "opp", "MaxChasiness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxThwackability", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxDivinity", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxMoxie", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxMusclitude", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxMartyrdom", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxLaserLikeness", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxBaseThirst", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxContinuation", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxGroundFriction", [[-2, 2]]),
#    MofoModTerm("WALK_IN_THE_PARK", "same", "MaxIndulgence", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "Ruthlessness", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "Unthwackability", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "Overpowerment", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "Shakespearianism", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "Coldness", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "MeanOmniscience", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "MeanTenaciousness", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "MeanWatchfulness", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "MeanAnticapitalism", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "MeanChasiness", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanTragicness", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanPatheticism", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanThwackability", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanDivinity", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanMoxie", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanMusclitude", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanMartyrdom", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanLaserlikeness", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanBaseThirst", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanContinuation", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanGroundFriction", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MeanIndulgence", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "MaxOmniscience", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "MaxTenaciousness", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "MaxWatchfulness", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "MaxAnticapitalism", [[-2, 2]]),
#    MofoModTerm("O_NO", "opp", "MaxChasiness", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MaxThwackability", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MaxDivinity", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MaxMoxie", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MaxMusclitude", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MaxMartyrdom", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MaxLaserLikeness", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MaxBaseThirst", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MaxContinuation", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MaxGroundFriction", [[-2, 2]]),
#    MofoModTerm("O_NO", "same", "MaxIndulgence", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "Ruthlessness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "Unthwackability", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "Overpowerment", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "Shakespearianism", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "Coldness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MeanOmniscience", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MeanTenaciousness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MeanWatchfulness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MeanAnticapitalism", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MeanChasiness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanTragicness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanPatheticism", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanThwackability", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanDivinity", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanMoxie", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanMusclitude", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanMartyrdom", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanLaserlikeness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanBaseThirst", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanContinuation", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanGroundFriction", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MeanIndulgence", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MaxOmniscience", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MaxTenaciousness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MaxWatchfulness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MaxAnticapitalism", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "opp", "MaxChasiness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxThwackability", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxDivinity", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxMoxie", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxMusclitude", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxMartyrdom", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxLaserLikeness", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxBaseThirst", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxContinuation", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxGroundFriction", [[-2, 2]]),
#    MofoModTerm("BASE_INSTINCTS", "same", "MaxIndulgence", [[-2, 2]])
#]
